logging:
    config: classpath:log4j2.xml

spring:
    application:
        name: app-card-processing
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: 0095
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                format_sql: true
        show-sql: true
    liquibase:
        change-log: classpath:db/changelog/db.changelog-master.yaml
    messages:
        basename: messages
        encoding: UTF-8

jwt:
    secretKey: ${JWT_KEY}
