logging:
    config: classpath:log4j2.xml
spring:
    application:
        name: app-card-processing
    datasource:
        driverClassName: org.postgresql.Driver
        password: 0095
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                format_sql: true
        show-sql: true
    liquibase:
        change-log: classpath:db/changelog/db.changelog-master.yaml
jwt:
    secretKey: ${JWT_KEY}